### ISSUE TITLE
GitHub Desktop

### ISSUE THREAD

**Issue by porkcube** [autopkg/homebysix-recipes#166]
Looks like they starting to be cute and use "Tasty Things Done Tastily" for their CFBundleShortVersionString but still incrementing CFBundleVersion.  Seems like the fix is explicating the `plist_version_key` in GitHubDesktop.download.recipe.

**Comment by homebysix** [comment]
@porkcube - GitHub Desktop has used "normal" versions ever since the app was rebuilt using the Electron framework. The current version is 1.1.1 (both CFBundleVersion and CFBundleShortVersionString).

Where are you seeing "Tasty Things Done Tastily?" That's suspiciously similar to the most recent pre-Electron version of the app: "Hasty Things Done Hastily." If you're getting that version upon running my recipes, it's probably because you have an old download URL specified in your override.

**Comment by porkcube** [comment]
Just created a fresh override from GitHubDesktop.munki.recipe (yours) and got the same https://central.github.com/mac/latest URL in my existing override.  Curl the file down and sure enough it's a new version (224 according to CFBundleVersion) and they're misusing CFBundleShortVersionString.

**Comment by homebysix** [comment]
Well, that's surprising. I didn't expect the non-Electron version of the app to be updated again.

The URL in my download recipe (which my Munki recipe uses as a parent) is not the one you linked above. (See [here](https://github.com/autopkg/homebysix-recipes/blob/ce0f2c7545cf82e7911cc154c5815fba794f8faf/GitHub/GitHubDesktop.download.recipe#L11-L12).) So I'm still curious where that URL came from in your override. Have you done a repo update recently?

In any case, I'm going to leave my recipe as is, because the Electron version of the app is clearly the one GitHub wants us to use now.

**Comment by porkcube** [comment]
Hrmm, yeah I update my autopkg repos every week or so but just tried again and it generated an override with the wrong URL that doesn't match your download recipe's.  Will poke things more on my side cause definitely not looking like your issue - thanks!
