### ISSUE TITLE
Zoom recipe installs the universal build and not the build for Apple Silicon on Apple M1 which causes issues.

### ISSUE THREAD

**Issue by sarthak0207** [autopkg/homebysix-recipes#445]

**Comment by homebysix** [comment]
Hi @sarthak0207 - Could you describe what issues you're encountering with the universal build that would be prevented by using an Apple Silicon only build? Steps to reproduce and screenshots would be useful, if applicable.

**Comment by sarthak0207** [comment]
> Hi @sarthak0207 - Could you describe what issues you're encountering with the universal build that would be prevented by using an Apple Silicon only build? Steps to reproduce and screenshots would be useful, if applicable.

Hi @homebysix , on Apple M1, the app is not able to auto update and getting update popups like below. . Thus if i have a standard user on the machine , and i try to update using the popup , then unless and until I promote the account to have administrator priveleges , I am not able to upgrade zoom .  

<img width="554" alt="Screenshot 2021-08-03 at 12 25 35 PM" src="https://user-images.githubusercontent.com/79002111/128542100-0b8d2fde-1e9f-4a11-8222-0a597d7c7ff0.png">

**Comment by jazzace** [comment]
I cannot replicate this on my M1 Mac mini. This is what I encountered running as a Standard User running the Universal version:
1. Launch Zoom 5.7.3
2. zoom.us > Check for Updates…
3. Update Available message appears
4. Click on the button to Update
5. Software is updated and app relaunches
To be clear, I am not using this recipe to get my Zoom for IT installer, I am using the MLBZ521-recipes version, so your result may vary.

**Comment by homebysix** [comment]
There's a lot to unpack here, so I'm going to respond in sections.

## IT Installer

My Zoom recipes leverage the Zoom "IT" installer, which is linked from [this KB article](https://support.zoom.us/hc/en-us/articles/115001799006-Mass-deployment-with-preconfigured-settings-for-Mac#h_5f9a35ec-92bf-4e3e-afb6-b365ab3ad3e4). Although I believe the differences between the IT installer and the consumer installer are fewer than before, the IT installer has been the preferred way to install Zoom using scalable software deployment systems like Jamf and Munki.

Even if we wanted to use the consumer installer (which I don't think we do), that change would need to happen in the [parent download recipe living in hansen-m-recipes](https://github.com/autopkg/hansen-m-recipes/blob/master/Zoom/Zoom.download.recipe#L14), not in my repo.

## Architecture

As far as I can tell, the IT installer is _only_ available in Universal flavor. Both the installer itself and the resulting app are Universal. The consumer Zoom installer is available in either Intel or Apple Silicon flavors, but not (yet) Universal. So I suspect it's the consumer installer you're referring to when you imply that there's a choice about which flavor to install.

Regardless, there should be no difference in behavior between a "universal" app and its "Apple Silicon only" counterpart on M1 systems. The latter should be a subset of the former.

## Permissions

I suspect there's more troubleshooting and reproduction needed, because this issue sounds a lot like a typical permissions issue to me. Apps that are deployed via software deployment systems are typically installed into the /Applications folder with "root" ownership. Local users will need administrative privileges in order to directly update these apps. I haven't reproduced your issue myself, but the behavior you're describing is in line with what I'd expect to see for a standard user.

Some IT teams who support standard users work around this by setting the app permissions to the logged-in user rather than to "root." Other IT teams disable the built-in updater and instead rely on their own software deployment system (e.g. Jamf, Munki) for patching.

Here's what I'd suggest:

1. Install a previous version of the Zoom IT installer on a test M1 Mac.
2. Log in as a non-admin user and attempt to update the app when prompted. You will probably not be able to.
3. Repeat steps 1 and 2 with the consumer Apple Silicon installer for Zoom.

If you're able to update as a non-admin user using one installer but not the other, please provide details about the permissions of the Zoom app in each iteration of your test: `ls -lad /Applications/zoom.us.app` 

Thank you!

**Comment by sarthak0207** [comment]
Thanks @homebysix for the detailed explanation. I too believe that the universal installer should not have differences with the consumer installer for M1 and seems like a permissions issue only and I'll try to check upon that with the steps you suggested . On a different note,  I am also using munki for software deployment. So, when you say  "Other IT teams disable the built-in updater and instead rely on their own software deployment system (e.g. Jamf, Munki) for patching."  So, how do they disable the built in updater. Is there a flag i can include in the recipe which i can use?

**Comment by homebysix** [comment]
@sarthak0207 There is a settings profile documented at the [same KB article](https://support.zoom.us/hc/en-us/articles/115001799006-Mass-deployment-with-preconfigured-settings-for-Mac?mobile_site=true#h_01EFZ819RBP2KK5AKKZ9S9QJQV) that describes the IT installer. Specifically, you may want to test setting the `zAutoUpdate` key to `false`. The profile can be distributed in one of several ways:

- Via MDM (this would be my recommendation)
- Via Munki as a `requires` or `update_for` (separate pkginfo item)
- Via Munki as a `preinstall_script` or `postinstall_script` for Zoom (contained in your Zoom.munki override)

Since I don't think your issue is with my AutoPkg recipe, I'm going to mark this issue closed. Thank you.
