### ISSUE TITLE
CakeBrew.download: URLDownloader stumbles over certificate

### ISSUE THREAD

**Issue by mihelm** [autopkg/homebysix-recipes#58]
Hi

This isn't an issue with the recipe but with the developer's/CDN's certificates.

SparkleUpdateInfoProvider finds the right url, but URLDownloader then downloads a .zip with zero bytes, which causes Unarchiver to fail. The url works when pasted into Safari, though it does object to the certificate due to hostname mismatch. Once the certificate has been trusted, the recipe runs through without a hitch. Not the pretties solution, but it works for anybody not minded to wait for the devs to sort out their certificates.

Anybody who doesn't want to accept such a certificate can download the latest version from GitHub instead. (Edit: My mistake, there's no downloadable installer for Cakebrew on GitHub.)

Cheers, michael.

**Comment by homebysix** [comment]
Hi @mihelm,

Good catch. It looks like the Cakebrew developer started linking to the CDN instead of the direct download in the Sparkle feed, as of the latest version.

![screen shot 2016-05-17 at 3 16 58 pm](https://cloud.githubusercontent.com/assets/7801391/15342009/155ea0f0-1c47-11e6-92ce-8e3501300727.png)

Since the CDN doesn't have a valid cert, the download fails.

I've rewritten the recipes to grab the direct download link from the front page of cakebrew.com instead of using the Sparkle feed. Can you check out the new [Cakebrew](https://github.com/autopkg/homebysix-recipes/tree/Cakebrew/Cakebrew) branch and let me know if that solves the problem for you?

Also, be aware that the Cakebrew recipe filenames and identifiers have (finally) been changed to reflect the correct capitalization. This is a one time change, and you may need to update your overrides or recipe_list.txt to match. I thought it was a good opportunity to make that change, since the recipes were already inoperative due to the CDN cert.

**Comment by mihelm** [comment]
Hi

Looks good, working on my setup.

Thanks — and thanks for all the recipes you've provided. I've used many of them! :-)

Cheers, michael.
